USE [master]
GO

/****** Object:  Database [DemoLibrary]    Script Date: 16/07/2015 10:36:13 a. m. ******/
CREATE DATABASE [DemoLibrary]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DemoLibrary', FILENAME = N'E:\MSSQL.MSSQLSERVER\DATA\DemoLibrary.mdf' , SIZE = 5120KB , MAXSIZE = 204800KB , FILEGROWTH = 5120KB )
 LOG ON 
( NAME = N'DemoLibrary_log', FILENAME = N'D:\MSSQL.MSSQLSERVER\DATA\DemoLibrary_log.ldf' , SIZE = 2048KB , MAXSIZE = 102400KB , FILEGROWTH = 5120KB )
GO

ALTER DATABASE [DemoLibrary] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DemoLibrary].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DemoLibrary] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DemoLibrary] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DemoLibrary] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DemoLibrary] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DemoLibrary] SET ARITHABORT OFF 
GO

ALTER DATABASE [DemoLibrary] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DemoLibrary] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DemoLibrary] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DemoLibrary] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DemoLibrary] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DemoLibrary] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DemoLibrary] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DemoLibrary] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DemoLibrary] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DemoLibrary] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DemoLibrary] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [DemoLibrary] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DemoLibrary] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DemoLibrary] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DemoLibrary] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DemoLibrary] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DemoLibrary] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DemoLibrary] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DemoLibrary] SET  MULTI_USER 
GO

ALTER DATABASE [DemoLibrary] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DemoLibrary] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DemoLibrary] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DemoLibrary] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DemoLibrary] SET  READ_WRITE 
GO


